global using Application;
global using Application.Model;
global using Host;
global using Host.Endpoints;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
global using System;